### PR TITLE
Reorganized viewmodels (Student, admin and user)

### PR DESCRIPTION
**Pull request by BjorniTe1**
The viewModels have been organized into subcategories (same as in the gRPC Manager and Server Provider).  These subcategories have been marked with MARK: commands so that they are easy to find.

Further work before we can leave draft PR:
- Some of the methods in the viewModels can be a bit ugly.  Make viewmodel methods easier to read for others.

### CODE REVIEW

**Comment by BjorniTe1** [comment]
Further work on AdminViewModel:
Check out if it is better to change from optional variables on users and courses to empty arrays.
By using empty arrays instead of optional variables we can go through the lists without checking if the variable is nil?

**Comment by BjorniTe1** [comment]
Further work on StudentViewModel:
- Check out if it is better to change from optional variables on submissions and assignments to empty arrays. By using empty arrays instead of optional variables we can go through the lists without checking if the variable is nil?
- Course do not have to be optional. StudentViewModel should not be able to be created without a course.

**Comment by BjorniTe1** [comment]
This PR Closes #81 , Closes #83

**Comment by BjorniTe1** [comment]
Will also add a reorganized teacherViewModel to this PR

**Review by oskargjolga — APPROVED** [review]

**Pull request merged**
